<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $customers = [
            [
                'customer_code' => 'CUST-1001',
                'name' => 'Johnathan Miller',
                'company_name' => 'Apex Mega Tech Supply Co.',
                'email' => 'jmiller@apexmegatech.com',
                'phone' => '+1 (555) 234-8901',
                'tier' => 'VIP Platinum',
                'wholesale_discount' => 20.00,
                'credit_limit' => 150000.00,
                'total_spent' => 485200.50,
                'total_orders' => 142,
                'payment_terms' => 'Net 60',
                'tax_id' => 'US-TX-9982341',
                'address' => '450 Industrial Parkway, Tech District',
                'city' => 'Austin',
                'country' => 'United States',
                'status' => 'active',
                'notes' => 'Top wholesale customer. Requires palletized delivery with liftgate service.',
            ],
            [
                'customer_code' => 'CUST-1002',
                'name' => 'Sarah Lin',
                'company_name' => 'Global Electronics Wholesale Inc.',
                'email' => 'sarah.lin@globalelectronics.io',
                'phone' => '+1 (555) 876-1234',
                'tier' => 'VIP Platinum',
                'wholesale_discount' => 18.50,
                'credit_limit' => 100000.00,
                'total_spent' => 320900.00,
                'total_orders' => 98,
                'payment_terms' => 'Net 30',
                'tax_id' => 'US-CA-7712390',
                'address' => '88 Silicon Enterprise Way',
                'city' => 'San Jose',
                'country' => 'United States',
                'status' => 'active',
                'notes' => 'High-volume monthly bulk RAM & GPU purchases.',
            ],
            [
                'customer_code' => 'CUST-1003',
                'name' => 'David Vance',
                'company_name' => 'Vance Computer Solutions Store',
                'email' => 'dvance@vancecomputers.com',
                'phone' => '+1 (555) 432-5678',
                'tier' => 'Wholesale Gold',
                'wholesale_discount' => 12.00,
                'credit_limit' => 50000.00,
                'total_spent' => 145800.75,
                'total_orders' => 54,
                'payment_terms' => 'Net 30',
                'tax_id' => 'US-NY-4482910',
                'address' => '120 Broadway Retail Mall, Suite 400',
                'city' => 'New York',
                'country' => 'United States',
                'status' => 'active',
                'notes' => 'Regular weekly restock orders for retail chain.',
            ],
            [
                'customer_code' => 'CUST-1004',
                'name' => 'Elena Rostova',
                'company_name' => 'EuroTech Bulk Logistics Ltd.',
                'email' => 'elena@eurotechbulk.eu',
                'phone' => '+44 20 7946 0912',
                'tier' => 'Wholesale Gold',
                'wholesale_discount' => 15.00,
                'credit_limit' => 75000.00,
                'total_spent' => 210450.00,
                'total_orders' => 67,
                'payment_terms' => 'Net 30',
                'tax_id' => 'GB-VAT-9018231',
                'address' => '14 Docklands Logistics Hub',
                'city' => 'London',
                'country' => 'United Kingdom',
                'status' => 'active',
                'notes' => 'International wholesale reseller across UK & EU markets.',
            ],
            [
                'customer_code' => 'CUST-1005',
                'name' => 'Marcus Thorne',
                'company_name' => 'Thorne Systems & Hardware Retail',
                'email' => 'mthorne@thornesystems.com',
                'phone' => '+1 (555) 312-9087',
                'tier' => 'Bulk Silver',
                'wholesale_discount' => 8.00,
                'credit_limit' => 25000.00,
                'total_spent' => 68400.00,
                'total_orders' => 29,
                'payment_terms' => 'Net 15',
                'tax_id' => 'US-IL-5531982',
                'address' => '742 Michigan Commerce Plaza',
                'city' => 'Chicago',
                'country' => 'United States',
                'status' => 'active',
                'notes' => 'Buys enterprise server parts & storage drives in volume batches.',
            ],
            [
                'customer_code' => 'CUST-1006',
                'name' => 'Kenji Sato',
                'company_name' => 'Nippon Hardware Supply Corp',
                'email' => 'sato.k@nipponhardware.jp',
                'phone' => '+81 3 5555 0143',
                'tier' => 'VIP Platinum',
                'wholesale_discount' => 22.00,
                'credit_limit' => 200000.00,
                'total_spent' => 612000.00,
                'total_orders' => 180,
                'payment_terms' => 'Net 60',
                'tax_id' => 'JP-TRN-1029384',
                'address' => '2-11 Akihabara Tech Trade Tower',
                'city' => 'Tokyo',
                'country' => 'Japan',
                'status' => 'active',
                'notes' => 'Key Asia-Pacific distributor. High credit rating with automated reorders.',
            ],
            [
                'customer_code' => 'CUST-1007',
                'name' => 'Amanda Rodriguez',
                'company_name' => 'Metro Retail Outlets Group',
                'email' => 'amanda@metroretailgroup.com',
                'phone' => '+1 (555) 678-4321',
                'tier' => 'Standard Wholesale',
                'wholesale_discount' => 5.00,
                'credit_limit' => 15000.00,
                'total_spent' => 24500.00,
                'total_orders' => 12,
                'payment_terms' => 'Cash on Delivery',
                'tax_id' => 'US-FL-3398102',
                'address' => '905 Ocean Commerce Blvd',
                'city' => 'Miami',
                'country' => 'United States',
                'status' => 'pending',
                'notes' => 'New wholesale account pending tier upgrade review after 5 more orders.',
            ],
            [
                'customer_code' => 'CUST-1008',
                'name' => 'Robert Chen',
                'company_name' => 'Pacific Hardware Outlets',
                'email' => 'rchen@pacific-hardware.com',
                'phone' => '+1 (555) 998-1122',
                'tier' => 'Bulk Silver',
                'wholesale_discount' => 10.00,
                'credit_limit' => 30000.00,
                'total_spent' => 89300.00,
                'total_orders' => 38,
                'payment_terms' => 'Net 15',
                'tax_id' => 'US-WA-8812903',
                'address' => '300 Puget Sound Trade Hub',
                'city' => 'Seattle',
                'country' => 'United States',
                'status' => 'inactive',
                'notes' => 'Account temporarily inactive due to seasonal store renovation.',
            ],
        ];

        foreach ($customers as $data) {
            Customer::updateOrCreate(
                ['customer_code' => $data['customer_code']],
                $data
            );
        }
    }
}
